{% set name = "pipenv" %}
{% set version = "2023.8.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fd61dcf257d0e4185e08fac44af1bea8e721ff32f94935f32ba3103dea2e08f7

build:
  noarch: python
  number: 0
  entry_points:
    - pipenv=pipenv:cli
    - pipenv-resolver=pipenv.resolver:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip >=18.0
    - python >=3.6
  run:
    - certifi
    - pip >=18.0
    - python >=3.7
    - setuptools >=36.2.1
    - virtualenv
    - virtualenv-clone >=0.2.5

test:
  commands:
    # pipenv attempts to detect a CI environment via
    #   PIPENV_IS_CI = env_to_bool(os.environ.get("CI") or os.environ.get("TF_BUILD") or False)
    #   https://github.com/pypa/pipenv/blob/114eb8f80a63e519fe9d12ac9e7cb60444cf47c0/pipenv/environments.py#L101
    #
    # This expects the envvar "CI" to be truthy, however CI=azure in
    # pipenv-feedstock.  Use CI=1 as workaround
    #
    # Related:
    # https://github.com/pypa/pipenv/pull/4944
    # https://github.com/pypa/pipenv/issues/4909
    - CI=1 python -c "import pipenv"
    - CI=1 pipenv --help

about:
  home: https://github.com/pypa/pipenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Development Workflow for Humans.
  doc_url: https://pipenv-fork.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - drewgilliam
    - roccqqck
