{% set name = "pipenv" %}
{% set version = "2024.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 422b09dc40798994a9641961983a1a4d1e831de8b91b2ad4d3d2ecb0ec42887c

build:
  noarch: python
  number: 1
  entry_points:
    - pipenv=pipenv:cli
    - pipenv-resolver=pipenv.resolver:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - setuptools >=67
  run:
    - python >=3.8
    - certifi
    - packaging >=22
    - setuptools >=67
    - virtualenv >=20.24.2

test:
  commands:
    # pipenv attempts to detect a CI environment via
    #   PIPENV_IS_CI = env_to_bool(os.environ.get("CI") or os.environ.get("TF_BUILD") or False)
    #   https://github.com/pypa/pipenv/blob/114eb8f80a63e519fe9d12ac9e7cb60444cf47c0/pipenv/environments.py#L101
    #
    # This expects the envvar "CI" to be truthy, however CI=azure in
    # pipenv-feedstock.  Use CI=1 as workaround
    #
    # Related:
    # https://github.com/pypa/pipenv/pull/4944
    # https://github.com/pypa/pipenv/issues/4909
    - CI=1 python -c "import pipenv"
    - CI=1 pipenv --help

about:
  home: https://github.com/pypa/pipenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Development Workflow for Humans.
  doc_url: https://pipenv-fork.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - drewgilliam
    - roccqqck
