{% set name = "pipenv" %}
{% set version = "2021.11.5.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f60ca33c355bce1af5eb743249f7d42a9c677df71bbfaf9d706e7ec06fae56f1

build:
  noarch: python
  number: 0
  entry_points:
    - pipenv=pipenv:cli
    - pewtwo=pipenv.patched.pew.pew:pew
    - pipenv-resolver=pipenv.resolver:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip >=18.0
    - python
  run:
    - certifi
    - pip >=18.0
    - python
    - setuptools >=36.2.1
    - virtualenv
    - virtualenv-clone >=0.2.5

test:
  imports:
    - pipenv

  commands:
    - pipenv --help

about:
  home: https://github.com/pypa/pipenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Development Workflow for Humans.
  doc_url: https://pipenv-fork.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - roccqqck
