{% set name = "pipenv" %}
{% set version = "2018.11.26" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a673e606e8452185e9817a987572b55360f4d28b50831ef3b42ac3cab3fee846

build:
  noarch: python
  number: 0
  entry_points:
    - pipenv=pipenv:cli
    - pewtwo=pipenv.patched.pew.pew:pew
    - pipenv-resolver=pipenv.resolver:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip >=9.0.1
    - python >=3.5
  run:
    - certifi
    - pip >=9.0.1
    - python >=3.5
    - setuptools >=36.2.1
    - virtualenv
    - virtualenv-clone >=0.2.5

test:
  imports:
    - pipenv

  commands:
    - pipenv --help

about:
  home: https://github.com/pypa/pipenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Python Development Workflow for Humans."
  doc_url: https://pipenv-fork.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - roccqqck
