{% set name = "pipenv" %}
{% set version = "2022.6.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ac0e7a8bbe02859d46c53c03d3f33136bbf49c8c7d9a6d818409e17a604eda0

build:
  noarch: python
  number: 0
  entry_points:
    - pipenv=pipenv:cli
    - pipenv-resolver=pipenv.resolver:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip >=18.0
    - python >=3.6
  run:
    - certifi
    - pip >=18.0
    - python >=3.6
    - setuptools >=36.2.1
    - virtualenv
    - virtualenv-clone >=0.2.5

test:
  imports:
    - pipenv
  commands:
    - pipenv --help

about:
  home: https://github.com/pypa/pipenv
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python Development Workflow for Humans.
  doc_url: https://pipenv-fork.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - roccqqck
